Improve error message for apply failures due to missing replica identity
pglogical doesn't comprehensively defend against enqueueing update/delete
changes that cannot be applied on the downstream due to lack of a REPLICA
IDENTITY candidate index. To help users understand this we need a better
error than

   ERROR: could not find primary key for table with oid 17975

See 2ndQuadrant/pglogical_internal#146