Merge pull request #163 from klando/master
Fix major-version detection on Pg10

pglogical wasn't correctly detecting tools by major-version only on pg10. It was treating "10.1" as the major, causing errors like

    ERROR:  pglogical subscriber init found pg_dump with wrong major version 10.1, expected 10.0