Remove ': Sucess' at the end of parameter parsing messages
Param parsing messages were emitting errors like:

ERROR:  could not parse integer value "borkbork" for parameter
"startup_params_format": Success
CONTEXT:  slot "test", output plugin "pglogical_output", in the startup
callback

because %m was used in the format string, but the underlying code
that parses the parameter never set an error message.

We could call the underlying parsing functions with the option
to throw an error on failure then PG_TRY and re-throw, but for
now it's not worth doing for a minor cosmetic bug. The user can
guess why we failed to parse the message well enough.

(Change originally by Pallavi, I just copy-edited the commit)